### ISSUE TITLE
Upgrade from 1.20.4 to 1.21.1 on /stop, small error msg

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/FarmersDance#4]
### Expected behavior

no error on /stop

### Observed/Actual behavior

```
[13:31:31 INFO]: [BentoBox-FarmersDance] Disabling BentoBox-FarmersDance v1.1.0-SNAPSHOT-b17
[13:31:31 ERROR]: Error occurred while disabling BentoBox-FarmersDance v1.1.0-SNAPSHOT-b17
java.lang.NullPointerException: Cannot invoke "world.bentobox.farmersdance.listeners.DancingHandler.stopTasks()" because "this.dancingHandler" is null
	at FarmersDance-1.1.0-SNAPSHOT-b17-1725703413831.jar/world.bentobox.farmersdance.FarmersDanceAddon.onDisable(FarmersDanceAddon.java:129) ~[FarmersDance-1.1.0-SNAPSHOT-b17-1725703413831.jar:?]
	at BentoBox-2.5.4-SNAPSHOT-b2711.jar/world.bentobox.bentobox.api.addons.Pladdon.onDisable(Pladdon.java:39) ~[BentoBox-2.5.4-SNAPSHOT-b2711.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:609) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1046) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[13:31:31 INFO]: [BentoBox-TopBlock] Disabling BentoBox-TopBlock v1.0.2-SNAPSHOT-b27
```

### Steps/models to reproduce

upgrade, and /stop

### BentoBox version

```
> bbox version
[12:12:54 INFO]: Running PAPER 1.21.1.
[12:12:54 INFO]: (1.21.1-65-21f125f (MC: 1.21.1))
[12:12:54 INFO]: BentoBox version: 2.5.4-SNAPSHOT-b2711
[12:12:54 INFO]: Database: JSON
[12:12:54 INFO]: Loaded Game Worlds:
[12:12:54 INFO]: acid (acid): Overworld
[12:12:54 INFO]: cave (cave): Overworld
[12:12:54 INFO]: oneblock (oneblock): Overworld
[12:12:54 INFO]: skyblock (skyblock): Overworld
[12:12:54 INFO]: skygrid (skygrid): Overworld
[12:12:54 INFO]: Loaded Addons:
[12:12:54 INFO]: AcidIsland 1.19.0 (ENABLED)
[12:12:54 INFO]: AOneBlock 1.17.1-SNAPSHOT-b413 (ENABLED)
[12:12:54 INFO]: Biomes 2.2.0-SNAPSHOT-b275 (ENABLED)
[12:12:54 INFO]: Border 4.3.1-SNAPSHOT-b212 (ENABLED)
[12:12:54 INFO]: BSkyBlock 1.18.1 (ENABLED)
[12:12:54 INFO]: CaveBlock 1.19.0 (ENABLED)
[12:12:54 INFO]: Challenges 1.3.2-SNAPSHOT-b564 (ENABLED)
[12:12:54 INFO]: FarmersDance 1.1.0-SNAPSHOT (ENABLED)
[12:12:54 INFO]: Greenhouses 1.8.0-SNAPSHOT-b375 (ENABLED)
[12:12:54 INFO]: Level 2.16.0-SNAPSHOT-b592 (ENABLED)
[12:12:54 INFO]: Limits 1.22.0 (ENABLED)
[12:12:54 INFO]: MagicCobblestoneGenerator 2.5.2-SNAPSHOT-b280 (ENABLED)
[12:12:54 INFO]: SkyGrid 2.1.1-SNAPSHOT-b436 (ENABLED)
[12:12:54 INFO]: TopBlock 1.0.2-SNAPSHOT-b27 (ENABLED)
[12:12:54 INFO]: Warps 1.15.1-SNAPSHOT-b372 (ENABLED)
>
```

### Plugin list

n/a

**Comment by Greymagic27** [comment]
Doesn't require upgrade. Running on a new 1.21.1 server and stopping with the addon will also cause the error

**Comment by tastybento** [comment]
All fixed.

**Comment by mrfloris** [comment]
Awesome.
